### ISSUE TITLE
rspec fails with S3 issue

### ISSUE THREAD

**Issue by tansaku** [enkanba/foodok#2]
running rspec I get a series of errors like:

```
  1) DishesController adding new dishes successfull creation calls Dish method to create a new dish
     Failure/Error:
       @s3_direct_post = S3_BUCKET.presigned_post(key: "dishes/#{SecureRandom.uuid}/${filename}", 
                         success_action_status: '201', acl: 'public-read')

     NoMethodError:
       undefined method `presigned_post' for nil:NilClass
       Did you mean?  presence_in
     # ./app/controllers/dishes_controller.rb:205:in `set_s3_direct_post'
     # /Users/tansaku/.rvm/gems/ruby-2.3.0/gems/rails-controller-testing-1.0.0/lib/rails/controller/testing/template_assertions.rb:61:in `process'
     # /Users/tansaku/.rvm/gems/ruby-2.3.0/gems/rails-controller-testing-1.0.0/lib/rails/controller/testing/integration.rb:12:in `block (2 levels) in <module:Integration>'
     # ./spec/controllers/dishes/dish_add_spec.rb:19:in `block (4 levels) in <top (required)>'

```
perhaps update your README.md with instructions about how to configure S3?

**Comment by enkanba** [comment]
Updated README with some instructions.
