### ISSUE TITLE
ideally should tests be stubbed and prevented from hitting S3

### ISSUE THREAD

**Issue by tansaku** [enkanba/foodok#4]
If running tests are hitting S3 that's a sign that automated tests will consume network resources - perhaps these need to be stubbed of sandboxed?

https://github.com/bblimke/webmock

https://github.com/vcr/vcr

**Comment by enkanba** [comment]
I agree with you, Sam. Will take note of this. I will keep this issue open until I fix it.

**Comment by enkanba** [comment]
Installed 'webmock' for mocking all non-local HTTP requests. Didn't have time to test it thoroughly though. My Travis-CI build seems to pass with webmock enabled.

**Comment by tansaku** [comment]
I still get fails locally:

```  31) DishesController generates view for new dish page for jasmine js testing
      Failure/Error:
        @s3_direct_post = S3_BUCKET.presigned_post(key: "dishes/#{SecureRandom.uuid}/${filename}", 
                          success_action_status: '201', acl: 'public-read')

      NoMethodError:
        undefined method `presigned_post' for nil:NilClass
        Did you mean?  presence_in
      # ./app/controllers/dishes_controller.rb:205:in `set_s3_direct_post'
      # /Users/tansaku/.rvm/gems/ruby-2.3.0/gems/rails-controller-testing-1.0.0/lib/rails/controller/testing/template_assertions.rb:61:in `process'
      # /Users/tansaku/.rvm/gems/ruby-2.3.0/gems/rails-controller-testing-1.0.0/lib/rails/controller/testing/integration.rb:12:in `block (2 levels) in <module:Integration>'
      # ./spec/fixtures/dish_new_spec.rb:16:in `block (2 levels) in <top (required)>'```

if wouter is up for it we could possibly look at webmock/vcr config this weekend in the context of exploring legacy apps

**Comment by enkanba** [comment]
Good idea!  Did you actually set-up env vars for S3 bucket as stated in the README ? I am not really sure that creating a credential object and bucket object needs a request towards aws over the net. see config/initializers/aws.rb
